config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kako/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("sigup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

templates/partials/footer.html
{% load i18n %}
<footer class="container py-10 mx-auto font-medium text-center text-gray-500 border-t">
  <div class="flex flex-col">
    <span>{% trans "Please don't copy us." %}</span>
    <span>&copy; 2020 Nbnb, Inc. {% trans "All rights reserved" %}.</span>
  </div>
  <div class="flex mt-10">
    {% get_current_language as LANGUAGE_CODE %}
    <select id="js-lang" class="w-1/5 h-8 p-0">
      <option value="en" 
        {% if LANGUAGE_CODE == 'en' %}
          selected
        {% endif %}
      >English</option>
      <option value="ko" 
        {% if LANGUAGE_CODE == 'es' %}
          selected
        {% endif %}
      >Spanish</option>
    </select>
  </div>
</footer>

templates/partials/messages.html
{% if messages %}
  <ul class="absolute top-0 left-0 right-0 flex justify-center mx-auto">
    {% for message in messages %}
    <li class="message font-medium bg-gray-700 z-10 w-40 text-center rounded-full text-white py-4 px-6 {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}

templates/partials/nav.html
{% load i18n %}

<ul class="flex items-center h-full text-sm font-medium">
  {% if user.is_authenticated %}
    <li class="nav_link">
      <a href="{% url 'users:switch-hosting' %}">
        {% if request.session.is_hosting %}
          {% trans "Stop hosting" %}
        {% else %}
          {% trans "Start hosting" %}
        {% endif %}
      </a>
    </li>
    {% if request.session.is_hosting %}
      <li class="nav_link"><a href="{% url "rooms:create" %}">{% trans "Create Room" %}</a></li>
    {% endif %}
    <li class="nav_link"><a href="{% url 'lists:see-favs' %}">{% trans "Favs" %} ({{user.list.rooms.count}})</a></li>
    <li class="nav_link"><a href="{{user.get_absolute_url}}">{% trans "Profile" %}</a></li>
    <li class="nav_link"><a href="{% url "users:logout" %}">{% trans "Log out" %}</a></li>
  {% else %}
    <li class="nav_link"><a href="{% url "users:login" %}">{% trans "Log in" %}</a></li>
    <li class="nav_link"><a href="{% url "users:signup" %}">{% trans "Sign Up" %}</a></li>
  {% endif %}
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
  <a href="{% url 'users:github-login' %}" class="w-full mb-2 font-medium text-gray-700 border-2 border-gray-700 btn">
    <i class="mr-2 fab fa-github-alt fa-lg"></i> Continue with Github
  </a>
  <a href="{% url 'users:kakao-login' %}" class="w-full mb-2 font-medium text-yellow-800 bg-yellow-400 border border-yellow-400 btn">
    <i class="mr-2 fas fa-comment fa-lg"></i> Continue with Kakao
  </a>
</div>

<div class="flex items-center w-full my-5">
  <div class="w-full h-px bg-gray-400"></div>
  <span class="mx-4 text-sm font-medium text-gray-600">or</span>
  <div class="w-full h-px bg-gray-400"></div>
</div>