config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse
from core import models as core_models
from django_countries.fields import CountryField
from cal import Calendar
# Create your models here.

class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)
    class Meta:
        abstract = True

    def __str__(self):
        return self.name

class RoomType(AbstractItem):

    """ RoomType Model Definition """
    pass

class Amenity(AbstractItem):

    """ Amenity Model Definition """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """ Facility Model Definition """

    pass

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ HouseRule Model Definition """

    class Meta:
        verbose_name = "House Rule"

 
class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to = "room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

class Room(core_models.TimeStampedModel):
    
    """ Room Model Definition """
    
    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField(help_text="How many people will be staying?")
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default = False)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE, null = True
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete = models.SET_NULL, null=True)

    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)
    
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

 
    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0

    def first_photo(self):
        try:
            photo, = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    
    def get_next_three_photos(self):
        photos = self.photos.all()[1:4]
        return photos

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        this_month = now.month
        next_month = this_month + 1
        if this_month == 12:
            next_month = 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(this_year, next_month)
        return [this_month_cal, next_month_cal]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms



# Create your views here.


class HomeView(ListView):

    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"


class RoomDetail(DetailView):

    """ RoomDetail Definition """

    model = models.Room


class SearchView(View):

    """ SearchView Definition """

    def get(self, request):

        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():

                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("-created")

                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )

        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form})


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room

class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Cant delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = ("caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):

    template_name = "rooms/photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Room Uploaded")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/photo_create.html
{% extends "base.html" %}

{% block page_title %}
    Upload photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
     
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Upload photo" %}
            
    </div>
{% endblock content %}

templates/rooms/photo_edit.html
{% extends "base.html" %}

{% block page_title %}
    Update photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
     
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Update photo" %}
            
    </div>
{% endblock content %}

templates/rooms/room_create.html
{% extends "base.html" %}

{% block page_title %}
    Create Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
     
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Create room" %}
            
    </div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}
{% load is_booked  i18n %}

{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{% block content %}

    <div class="-mt-5 container max-w-full h-75vh flex mb-20">
        <div class="h-full w-1/2 bg-center bg-cover" style="background-image:url({{room.first_photo}})"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div style="background-image:url({{photo.file.url}})" class="w-1/2 h-auto bg-cover bg-center border-gray-700 border"></div>
            {% endfor %}
        </div>
    </div>

    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{room.name}}</h4>
                    <span class="text-gray-700 font-light">{{room.city}}</span>
                </div>
                <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=room.host %}
                    <span class="mt-2 text-gray-500">{{room.host.first_name}}</span>
                </a>
            </div>
            
                <a class="block mb-10 w-2/6 text-teal-600 font-bold" href="{% url 'lists:toggle-room' room.pk %}?action=remove">{% trans "Remove from Favourites" %}</a>
            
                <a class="block mb-10 w-2/6 text-teal-600 font-bold" href="{% url 'lists:toggle-room' room.pk %}?action=add">{% trans "Save to Favourites" %}</a>
            
            
            <div class="flex border-section">
                <span class="mr-5 font-light">{{room.room_type}}</span>
                <span class="mr-5 font-light">{{room.beds}} bed{{room.beds|pluralize}}</span>
                <span class="mr-5 font-light">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
                <span class="mr-5 font-light">{{room.baths}} bath{{room.baths|pluralize}}</span>
                <span class="mr-5 font-light">{{room.guests}} guest{{room.guests|pluralize}}</span>
            </div>
            <p class="border-section">
                {{room.description}}
            </p>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Amenities</h4>
                {% for a in room.amenities.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Facilities</h4>
                {% for a in room.facilities.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">House Rules</h4>
                {% for a in room.house_rules.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="mt-10">
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-teal-500"></i>
                        <span class="font-bold text-xl">{{room.total_rating}}</span>
                    </div>
                    <div class="h-4 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{room.reviews.count}}</span>
                        <span>review{{room.reviews.count|pluralize}}</span>
                    </div>
                </div>
                <div class="mt-10">
                    {% for review in room.reviews.all  %}
                        <div class="border-section">
                            <div class="mb-3 flex">
                                <div>
                                    {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='text-xl' %}
                                </div>
                                <div class="flex flex-col ml-5">
                                    <span class="font-medium">{{review.user.first_name}}</span>
                                    <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                                </div>
                            </div>
                            <p>{{review.review}}</p>
                        </div>
                    {% endfor %}    
                </div>
            </div>
        </div>
        <div class="w-1/3">
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Edit Room</a>
            {% else %}
                {% if not request.session.is_hosting %}
                    {% for calendar in room.get_calendars %}
                    <div class="mb-20">        
                        <span class="text-center font-semibold text-lg block mb-8">{{calendar.get_month}} / {{calendar.year}}</span>
                        <div class="cal-grid font-medium mb-4">
                            {% for day in calendar.day_names  %}
                                <span>{{day}}</span>
                            {% endfor %}
                        </div>
                        <div class="cal-grid">
                            {% for day in calendar.get_days  %}
                                {% is_booked room day as is_booked_bool %}
                                {% if day.number != 0 %}
                                    {% if day.past %}
                                        <span class="cal-number bg-gray-200 text-gray-400">{{day}}</span>
                                    {% elif is_booked_bool %}
                                        <span class="cal-number bg-gray-200 text-gray-400 line-through">{{day}}</span>
                                    {% else %}
                                        <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}" class="cal-number bg-gray-200 text-gray-700 hover:bg-teal-400 hover:text-white hover:font-medium">{{day}}</a>
                                    {% endif %}
                                {% else %}
                                  <span></span>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
     
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Update room" %}

        <div class="mt-5">
            <a href="{% url 'rooms:photos' room.pk %}" class="text-teal-500 font-medium">Edit Photos</a>
        </div>
            
    </div>
{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page_name %}
	Home
{% endblock page_name %}

{% block content %}

	<div class="container pb-10 mx-auto">
		<div class="container mx-auto mt-32 mb-24 bg-gray-800 bg-center bg-cover rounded-xl h-50vh" style="background-image:url(https://images.unsplash.com/photo-1545071427-1e8f559966d6?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80)">
		</div>

    <div class="flex flex-wrap mb-10">
		{% for room in rooms  %}
      {% include 'mixins/room_card.html' with room=room %}
		{% endfor %}
    </div>

		<div class="container flex items-center justify-center mx-auto">
			{% if page_obj.has_previous %}
				<a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
					<i class="fas fa-arrow-left fa-lg"></i>
				</a>
			{% endif %}

			<span class="mx-3 text-lg font-medium">
        {% blocktrans with current_page=page_obj.number total_pages=page_obj.paginator.num_pages %}Page {{current_page}} of {{total_pages}}{% endblocktrans %}
      </span>
			
			{% if page_obj.has_next  %}
				<a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
					<i class="fas fa-arrow-right fa-lg"></i>
				</a>
			{% endif %}
		</div>
	</div>


{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
    {{room.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
     
    <div class="container mx-auto my-10 flex flex-col">

        <div class="my-10 w-full">
            <a href="{% url 'rooms:add-photo' room.pk %}" class="btn-link w-1/6 block">Upload Photo</a>
        </div>

        {% for photo in room.photos.all  %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32" />
                    <span class="ml-5 text-xl">{{photo.caption}}</span>
                </div>
                <div class="flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-teal-500" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
                    <a class="btn-link bg-red-600" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
                </div>
            </div>
        {% endfor %}

        <div class="flex justify-center mt-5">
            <a href="{% url 'rooms:edit' room.pk %}" class="text-teal-500 font-medium text-xl">Back to edit room</a>
        </div>
            
    </div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <h2>Search!</h2>

    <form method="get" action="{% url "rooms:search" %}">
        {{form.as_p}}
        <button>Search</button>
    </form>

    <h3>Results</h3>

    {% for room in rooms %}
        <h3>{{room.name}}</h3>
    {% endfor %}


{% endblock content %}